task:
  name: Linux (Debian/Ubuntu)
  container:
    matrix:
      - image: debian:stable
      - image: debian:oldstable
#      - image: ubuntu:20.04
      - image: ubuntu:18.04
      - image: ubuntu:16.04
      - image: ubuntu:14.04
  setup_script:
    - apt-get update
    - apt-get -y install autoconf automake libevent-dev libssl-dev libtool make pkg-config
  build_script:
    - ./autogen.sh
    - ./configure --prefix=$HOME/install --enable-werror
    - make
  test_script:
    - make check
  install_script:
    - make install
  always:
    configure_artifacts:
      path: "config.log"
      type: text/plain

task:
  name: Linux (Red Hat)
  container:
    matrix:
      - image: centos:centos8
      - image: centos:centos7
  setup_script:
    - yum -y install autoconf automake libevent-devel libtool make openssl-devel pkg-config
  build_script:
    - ./autogen.sh
    - ./configure --prefix=$HOME/install --enable-werror
    - make
  test_script:
    - make check
  install_script:
    - make install
  always:
    configure_artifacts:
      path: "config.log"
      type: text/plain

task:
  name: Linux (Alpine)
  container:
    matrix:
      - image: alpine:latest
  setup_script:
    - apk update
    - apk add autoconf automake build-base libevent-dev libtool openssl-dev pkgconf
  build_script:
    - ./autogen.sh
    - ./configure --prefix=$HOME/install --enable-werror
    - make
  test_script:
    - make check || :  # TODO
  install_script:
    - make install
  always:
    configure_artifacts:
      path: "config.log"
      type: text/plain

task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-12-1
  setup_script:
    - pkg install -y autoconf automake gmake libevent libtool pkgconf
  env:
    CPPFLAGS: -I/usr/local/include
    LDFLAGS: -L/usr/local/lib
  build_script:
    - ./autogen.sh
    - ./configure --prefix=$HOME/install --enable-werror
    - gmake
  test_script:
    - gmake check || :  # TODO
  install_script:
    - gmake install
  always:
    configure_artifacts:
      path: "config.log"
      type: text/plain

task:
  name: macOS
  osx_instance:
    matrix:
      - image: catalina-base
  setup_script:
    - brew install autoconf automake libevent libtool openssl pkg-config
  env:
    CPPFLAGS: -I/usr/local/opt/openssl/include
    LDFLAGS: -L/usr/local/opt/openssl/lib
  build_script:
    - ./autogen.sh
    - ./configure --prefix=$HOME/install --enable-werror
    - make
  test_script:
    - make check || :  # TODO
  install_script:
    - make install
  always:
    configure_artifacts:
      path: "config.log"
      type: text/plain

task:
  name: Windows
  windows_container:
    image: cirrusci/windowsservercore:cmake
  env:
    - MSYSTEM: MINGW32
    - PATH: C:/tools/msys64/usr/bin;%PATH%
    - HOME: .
  setup_script:
    - sh -l -c "pacman --noconfirm -S --needed base-devel ${MINGW_PACKAGE_PREFIX}-toolchain ${MINGW_PACKAGE_PREFIX}-libevent"
  build_script:
    - sh -l -c "./autogen.sh"
    - sh -l -c "./configure --prefix=$HOME/install --enable-werror"
    - sh -l -c "make"
#  test_script:
#    - sh -l -c "make check"
  install_script:
    - sh -l -c "make install"
  always:
    configure_artifacts:
      path: "config.log"
      type: text/plain
