dist: bionic
language: c
addons:
  apt:
    update: true
    packages:
      - libevent-dev
jobs:
  include:
  - env: configure_args=''
  - env: configure_args='--enable-cassert'
  - env: configure_args='--enable-cassert --with-uregex'
  - compiler: clang
  - dist: trusty
  - dist: xenial
  - arch: arm64
  - arch: ppc64le
script: |
  set -e
  ./autogen.sh
  ./configure --prefix=$HOME/install --disable-werror $configure_args
  make
  make check
  make install
